[package]
name = "auto-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
livesplit-wrapper = { path = "../../livesplit-wrapper" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
panic = "abort"
