[package]
name = "auto-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
livesplit-wrapper = { git = "https://github.com/P1n3appl3/livesplit-wrapper" }
log = "0.4"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
panic = "abort"
